apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbom-security-pipeline
  labels:
    app: sbom-security-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbom-security-pipeline
  template:
    metadata:
      labels:
        app: sbom-security-pipeline
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: app
        image: ghcr.io/username/sbom-security-pipeline:latest
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}