apiVersion: v1
kind: Service
metadata:
  name: sbom-security-pipeline
  labels:
    app: sbom-security-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sbom-security-pipeline