# ⚡ Event-Driven Ansible (EDA) Complete Setup
# Production-ready EDA deployment with N8N integration

version: '3.8'

services:
  # Ansible EDA Controller
  eda-controller:
    image: quay.io/ansible/eda-server:latest
    container_name: eda-controller
    restart: unless-stopped
    ports:
      - "8000:8000"  # EDA Web UI
      - "5000:5000"  # Webhook endpoints
      - "5001:5001"  # Additional webhook port
    environment:
      - EDA_DB_HOST=postgres
      - EDA_DB_PORT=5432
      - EDA_DB_NAME=eda
      - EDA_DB_USER=eda
      - EDA_DB_PASSWORD=${EDA_DB_PASSWORD:-eda_password_123}
      - EDA_SECRET_KEY=${EDA_SECRET_KEY:-eda-secret-key-change-me}
      - EDA_ALLOWED_HOSTS=localhost,127.0.0.1,eda-controller
      - EDA_DEBUG=false
    volumes:
      - ./rulebooks:/opt/eda/rulebooks:ro
      - ./playbooks:/opt/eda/playbooks:ro
      - ./inventory:/opt/eda/inventory:ro
      - ./collections:/opt/eda/collections:ro
      - eda_projects:/opt/eda/projects
      - eda_logs:/var/log/eda
    depends_on:
      - postgres
      - redis
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=eda-controller"
      - "com.devsecops.component=automation"

  # Ansible EDA Worker
  eda-worker:
    image: quay.io/ansible/eda-server:latest
    container_name: eda-worker
    restart: unless-stopped
    command: ["eda-server", "rq", "worker"]
    environment:
      - EDA_DB_HOST=postgres
      - EDA_DB_PORT=5432
      - EDA_DB_NAME=eda
      - EDA_DB_USER=eda
      - EDA_DB_PASSWORD=${EDA_DB_PASSWORD:-eda_password_123}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./rulebooks:/opt/eda/rulebooks:ro
      - ./playbooks:/opt/eda/playbooks:ro
      - ./inventory:/opt/eda/inventory:ro
      - eda_projects:/opt/eda/projects
      - eda_logs:/var/log/eda
    depends_on:
      - postgres
      - redis
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=eda-worker"
      - "com.devsecops.component=automation"

  # PostgreSQL Database for EDA
  postgres:
    image: postgres:15-alpine
    container_name: eda-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eda
      - POSTGRES_USER=eda
      - POSTGRES_PASSWORD=${EDA_DB_PASSWORD:-eda_password_123}
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=postgres"
      - "com.devsecops.component=database"

  # Redis for EDA task queue
  redis:
    image: redis:7-alpine
    container_name: eda-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=redis"
      - "com.devsecops.component=cache"

  # N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-devsecops
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD:-n8n_password_123}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-n8n_admin_123}
      - WEBHOOK_URL=https://n8n.local
      - GENERIC_TIMEZONE=UTC
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168  # 7 days
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    depends_on:
      - postgres
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=n8n"
      - "com.devsecops.component=workflow-automation"

  # Webhook Proxy/Router
  webhook-router:
    image: nginx:alpine
    container_name: webhook-router
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - eda-controller
      - n8n
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=webhook-router"
      - "com.devsecops.component=proxy"

  # Monitoring for EDA/N8N
  monitoring:
    image: prom/prometheus:latest
    container_name: eda-monitoring
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus-eda.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_eda_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=monitoring"
      - "com.devsecops.component=observability"

  # Log Aggregation for EDA
  fluentd:
    image: fluentd:v1.16-debian-1
    container_name: eda-fluentd
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
      - eda_logs:/var/log/eda:ro
    networks:
      - eda-network
    labels:
      - "com.devsecops.service=fluentd"
      - "com.devsecops.component=logging"

volumes:
  eda_projects:
    driver: local
    labels:
      - "com.devsecops.volume=eda-projects"
      
  eda_logs:
    driver: local
    labels:
      - "com.devsecops.volume=eda-logs"
      
  postgres_data:
    driver: local
    labels:
      - "com.devsecops.volume=postgres-data"
      
  redis_data:
    driver: local
    labels:
      - "com.devsecops.volume=redis-data"
      
  n8n_data:
    driver: local
    labels:
      - "com.devsecops.volume=n8n-data"
      
  prometheus_eda_data:
    driver: local
    labels:
      - "com.devsecops.volume=prometheus-eda-data"

networks:
  eda-network:
    driver: bridge
    labels:
      - "com.devsecops.network=eda"
    ipam:
      config:
        - subnet: 172.30.0.0/16