name: Terraform Plan (PR)

on:
  pull_request:
    paths:
      - 'terraform/**'

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "005965605891"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: |
          cd $TF_WORKING_DIR && terraform init -input=false
      - name: Terraform Validate & FMT
        run: |
          set -e
          cd $TF_WORKING_DIR
          terraform fmt -check
          terraform validate
      - name: Terraform Plan (JSON)
        run: |
          cd $TF_WORKING_DIR
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: $TF_WORKING_DIR/plan.json
